"""
Management command: seed_multidisciplinary
-------------------------------------------
Generates high-quality MCQ assessments for diverse academic fields so that
every user — regardless of their discipline — finds relevant practice content
on EduReach.

Fields covered:
  medicine, nursing, pharmacy, chemistry, biology, architecture, law,
  business, accounting, computer_science, agriculture, education

Each topic → 1 Assessment with 12 MCQ questions generated by AI.

Usage:
    python manage.py seed_multidisciplinary --dry-run
    python manage.py seed_multidisciplinary                        # all fields
    python manage.py seed_multidisciplinary --fields medicine,nursing,law
    python manage.py seed_multidisciplinary --fields chemistry --update

Notes:
    - Skips assessments that already exist (by title) unless --update is passed.
    - Costs ~50–80K tokens total for all fields at 12q each (~$0.05-0.15).
    - Each generated question is reviewed for quality: must have 4 options
      and a correct answer; questions that fail are discarded.
"""

import json
import re
import time
import logging

from django.core.management.base import BaseCommand
from django.conf import settings

logger = logging.getLogger(__name__)

# ── Subject definitions ───────────────────────────────────────────────────────
# Each field: list of (assessment_title, topic_hint, [tags])
SUBJECTS = {
    'medicine': {
        'display': 'Medicine & Clinical Sciences',
        'topics': [
            ('Human Anatomy — Musculoskeletal System',
             'muscles, bones, joints, skeletal anatomy, tendons, ligaments',
             ['medicine', 'anatomy', 'musculoskeletal', 'mbbs', 'healthcare']),
            ('Human Physiology — Cardiovascular System',
             'heart, cardiac cycle, blood pressure, circulation, ECG',
             ['medicine', 'physiology', 'cardiology', 'cardiovascular', 'healthcare']),
            ('Pharmacology — Antibiotics & Antimicrobials',
             'antibiotics, penicillin, beta-lactams, drug resistance, mechanisms of action',
             ['medicine', 'pharmacology', 'antibiotics', 'drugs', 'healthcare']),
            ('Pathology — Infectious Diseases',
             'bacterial infections, viral infections, immunity, inflammation, diagnosis',
             ['medicine', 'pathology', 'infectious diseases', 'diagnosis', 'healthcare']),
            ('Biochemistry — Metabolism & Enzymes',
             'glycolysis, TCA cycle, enzymes, metabolic pathways, ATP production',
             ['medicine', 'biochemistry', 'metabolism', 'enzymes', 'mbbs']),
        ],
    },
    'nursing': {
        'display': 'Nursing & Midwifery',
        'topics': [
            ('Nursing Fundamentals — Patient Care & Safety',
             'patient assessment, vital signs, wound care, infection control, bed making, patient positioning',
             ['nursing', 'patient care', 'fundamentals', 'healthcare', 'clinical']),
            ('Drug Dosage Calculations for Nurses',
             'drug dosage calculations, IV drip rate, paediatric dosing, weight-based dosing, unit conversion',
             ['nursing', 'pharmacology', 'dosage calculations', 'medication', 'healthcare']),
            ('Maternal & Child Health Nursing',
             'antenatal care, postnatal care, breastfeeding, newborn assessment, obstetrics complications',
             ['nursing', 'midwifery', 'maternal health', 'child health', 'obstetrics']),
            ('Mental Health Nursing',
             'psychiatric disorders, schizophrenia, depression, anxiety, therapeutic communication, mental health assessment',
             ['nursing', 'mental health', 'psychiatry', 'therapeutic communication']),
            ('Community Health & Public Health Nursing',
             'community health, disease prevention, health promotion, immunisation, epidemiology',
             ['nursing', 'community health', 'public health', 'epidemiology', 'healthcare']),
        ],
    },
    'pharmacy': {
        'display': 'Pharmacy & Pharmaceutical Sciences',
        'topics': [
            ('Pharmaceutics — Drug Formulation & Delivery',
             'drug formulation, tablets, capsules, bioavailability, pharmacokinetics, routes of administration',
             ['pharmacy', 'pharmaceutics', 'drug delivery', 'formulation', 'healthcare']),
            ('Pharmacology — Drug Mechanisms & Side Effects',
             'drug receptors, agonists, antagonists, side effects, drug interactions, therapeutic index',
             ['pharmacy', 'pharmacology', 'drug mechanisms', 'side effects', 'healthcare']),
            ('Pharmaceutical Chemistry',
             'drug synthesis, chemical structure, stereochemistry, SAR, organic chemistry in drugs',
             ['pharmacy', 'pharmaceutical chemistry', 'drug synthesis', 'organic chemistry']),
        ],
    },
    'chemistry': {
        'display': 'Chemistry',
        'topics': [
            ('Organic Chemistry — Reactions & Mechanisms',
             'substitution reactions, elimination, addition, carbonyl chemistry, reaction mechanisms, functional groups',
             ['chemistry', 'organic chemistry', 'reactions', 'mechanisms', 'university']),
            ('Analytical Chemistry — Titrations & Spectroscopy',
             'acid-base titration, redox titration, UV-vis spectroscopy, chromatography, quantitative analysis',
             ['chemistry', 'analytical chemistry', 'titration', 'spectroscopy']),
            ('Physical Chemistry — Thermodynamics & Kinetics',
             'enthalpy, entropy, Gibbs free energy, reaction rates, activation energy, equilibrium constants',
             ['chemistry', 'physical chemistry', 'thermodynamics', 'kinetics']),
            ('Inorganic Chemistry — Periodic Table & Bonding',
             'periodic trends, chemical bonding, ionic compounds, transition metals, coordination compounds',
             ['chemistry', 'inorganic chemistry', 'periodic table', 'bonding']),
        ],
    },
    'biology': {
        'display': 'Biology & Life Sciences',
        'topics': [
            ('Cell Biology & Genetics',
             'cell structure, mitosis, meiosis, DNA replication, gene expression, Mendelian genetics',
             ['biology', 'cell biology', 'genetics', 'DNA', 'university']),
            ('Ecology & Environmental Biology',
             'ecosystems, food chains, biodiversity, population dynamics, climate change, conservation',
             ['biology', 'ecology', 'environment', 'ecosystems', 'conservation']),
            ('Microbiology — Bacteria, Viruses & Fungi',
             'bacterial structure, viral replication, fungal infections, sterilisation, laboratory techniques',
             ['biology', 'microbiology', 'bacteria', 'viruses', 'laboratory']),
        ],
    },
    'architecture': {
        'display': 'Architecture & Built Environment',
        'topics': [
            ('Architectural Design Theory & History',
             'design principles, architectural history, modernism, vernacular architecture, form and function',
             ['architecture', 'design theory', 'architectural history', 'built environment']),
            ('Structural Engineering for Architects',
             'loads, beams, columns, structural systems, foundations, material strength',
             ['architecture', 'structural engineering', 'loads', 'construction']),
            ('Construction Materials & Technology',
             'concrete, steel, timber, glass, masonry, building materials properties, sustainability',
             ['architecture', 'construction materials', 'technology', 'building']),
            ('Building Services & Environmental Design',
             'HVAC, natural ventilation, daylighting, acoustic design, plumbing, electrical systems',
             ['architecture', 'building services', 'environmental design', 'sustainability']),
        ],
    },
    'law': {
        'display': 'Law & Legal Studies',
        'topics': [
            ('Constitutional Law — Kenya',
             'Kenya Constitution 2010, fundamental rights, devolution, separation of powers, Bill of Rights',
             ['law', 'constitutional law', 'kenya', 'rights', 'governance']),
            ('Law of Contract',
             'offer and acceptance, consideration, capacity, misrepresentation, breach of contract, remedies',
             ['law', 'contract law', 'obligations', 'agreements', 'commercial law']),
            ('Criminal Law & Procedure',
             'criminal offences, mens rea, actus reus, defences, criminal procedure, sentencing',
             ['law', 'criminal law', 'procedure', 'offences', 'courts']),
            ('Law of Tort',
             'negligence, duty of care, defamation, nuisance, occupiers liability, vicarious liability',
             ['law', 'tort', 'negligence', 'liability', 'civil law']),
            ('Company & Business Law',
             'company formation, directors, shareholders, partnerships, business contracts, insolvency',
             ['law', 'company law', 'business law', 'commercial', 'kenya']),
        ],
    },
    'business': {
        'display': 'Business & Management',
        'topics': [
            ('Financial Accounting — Principles & Practice',
             'double entry bookkeeping, trial balance, balance sheet, income statement, cash flow, IFRS',
             ['business', 'accounting', 'financial accounting', 'bookkeeping', 'IFRS']),
            ('Business Management & Strategy',
             'strategic management, SWOT analysis, competitive advantage, organisational structure, leadership',
             ['business', 'management', 'strategy', 'leadership', 'organisations']),
            ('Marketing Fundamentals',
             'marketing mix, consumer behaviour, market segmentation, branding, digital marketing, pricing',
             ['business', 'marketing', 'consumer behaviour', 'branding', 'sales']),
            ('Entrepreneurship & Business Planning',
             'business plan, startup, funding, value proposition, market analysis, financial projections',
             ['business', 'entrepreneurship', 'startup', 'business plan', 'kenya']),
        ],
    },
    'accounting': {
        'display': 'Accounting & Finance',
        'topics': [
            ('Management Accounting — Cost & Budgeting',
             'cost classification, break-even analysis, budgeting, variance analysis, absorption costing',
             ['accounting', 'management accounting', 'cost accounting', 'budgeting', 'finance']),
            ('Financial Management & Investment',
             'time value of money, NPV, IRR, capital budgeting, risk and return, portfolio management',
             ['accounting', 'finance', 'investment', 'capital budgeting', 'financial management']),
            ('Taxation — Kenya Revenue Authority',
             'income tax, VAT, PAYE, withholding tax, KRA, tax compliance, tax computation',
             ['accounting', 'taxation', 'KRA', 'kenya', 'tax law', 'finance']),
        ],
    },
    'computer_science': {
        'display': 'Computer Science & IT',
        'topics': [
            ('Data Structures & Algorithms',
             'arrays, linked lists, stacks, queues, trees, sorting algorithms, time complexity, Big-O notation',
             ['computer science', 'data structures', 'algorithms', 'programming', 'university']),
            ('Database Management Systems',
             'relational databases, SQL, normalisation, ER diagrams, transactions, ACID properties, indexing',
             ['computer science', 'databases', 'SQL', 'RDBMS', 'information systems']),
            ('Computer Networks & Security',
             'OSI model, TCP/IP, HTTP, DNS, firewalls, encryption, cybersecurity, network protocols',
             ['computer science', 'networks', 'cybersecurity', 'protocols', 'IT']),
            ('Operating Systems',
             'process management, memory management, file systems, CPU scheduling, deadlocks, virtualisation',
             ['computer science', 'operating systems', 'OS', 'systems programming']),
        ],
    },
    'agriculture': {
        'display': 'Agriculture & Food Science',
        'topics': [
            ('Crop Science & Agronomy',
             'crop production, soil fertility, irrigation, pest management, crop rotation, yield improvement',
             ['agriculture', 'crop science', 'agronomy', 'farming', 'food security']),
            ('Animal Science & Livestock Management',
             'livestock breeds, animal nutrition, veterinary basics, reproduction, milk production, poultry',
             ['agriculture', 'animal science', 'livestock', 'veterinary', 'farming']),
            ('Soil Science & Land Management',
             'soil types, soil pH, soil organic matter, erosion control, fertilisers, sustainable farming',
             ['agriculture', 'soil science', 'land management', 'sustainability']),
        ],
    },
    'education': {
        'display': 'Education & Teaching',
        'topics': [
            ('Educational Psychology & Learning Theories',
             'Piaget, Vygotsky, Bloom taxonomy, constructivism, behaviourism, cognitive development',
             ['education', 'educational psychology', 'learning theories', 'teaching']),
            ('Curriculum Development & Lesson Planning',
             'curriculum design, lesson planning, learning objectives, assessment methods, differentiated instruction',
             ['education', 'curriculum', 'lesson planning', 'pedagogy', 'teaching']),
            ('Special Needs Education & Inclusion',
             'learning disabilities, autism, dyslexia, inclusive education, IEP, assistive technology',
             ['education', 'special needs', 'inclusion', 'disabilities', 'pedagogy']),
        ],
    },
}

# ── AI Question Generator ─────────────────────────────────────────────────────

MCQ_MODEL   = 'google/gemini-2.0-flash-001'
EXAM_MODEL  = 'google/gemini-2.0-flash-001'

MCQ_PROMPT = """You are an expert educator creating a high-quality multiple-choice practice quiz for university students.

Field: {field_display}
Topic: {title}
Subject focus: {hint}

Generate exactly 10 multiple-choice questions. Requirements:
- Clearly worded, educationally accurate, appropriately challenging for university level
- Each question must have exactly 4 options as a JSON list
- One option must be correct; the other three must be plausible (not obviously wrong)
- Include a brief explanation (1–2 sentences) for the correct answer
- Cover different subtopics within the subject focus
- Difficulty mix: 3 easy, 5 medium, 2 challenging

Respond ONLY with valid JSON (no markdown, no extra text):
{{
  "questions": [
    {{
      "question_text": "...",
      "options": ["Option A text", "Option B text", "Option C text", "Option D text"],
      "correct_answer": "Option A text",
      "explanation": "..."
    }}
  ]
}}"""


EXAM_PROMPT = """You are an experienced university lecturer in {field_display} setting an end-of-semester examination paper in the style of Kenyan universities (Kenyatta University format).

Topic: {title}
Subject focus: {hint}

Create an examination paper with THREE sections:

SECTION A — Multiple Choice (5 questions, 2 marks each = 10 marks, ALL compulsory)
- Short, direct MCQ questions with exactly 4 options as a JSON list
- Include correct_answer (full text of the correct option) and explanation

SECTION B — Short Answer Questions (3 questions, 10 marks each — student attempts ANY 2 = 20 marks)
- Each question should have 2–3 sub-parts (i, ii, iii)
- Requires written explanation, calculation, or short paragraphs
- Marks allocation shown per sub-part
- No options (empty list []); correct_answer should be a model answer (3–5 sentences)

SECTION C — Essay / Long Answer (2 questions, 20 marks each — student attempts ANY 1 = 20 marks)
- Broad, analytical questions requiring extended written response
- Include marking guidance in the explanation
- No options (empty list []); correct_answer should be a comprehensive model answer

Respond ONLY with valid JSON (no markdown, no extra text):
{{
  "questions": [
    {{
      "section": "A",
      "question_text": "...",
      "options": ["Option A text", "Option B text", "Option C text", "Option D text"],
      "correct_answer": "Option A text",
      "explanation": "...",
      "points": 2
    }},
    {{
      "section": "B",
      "question_text": "(a) ... [4 marks]\\n(b) ... [3 marks]\\n(c) ... [3 marks]",
      "options": [],
      "correct_answer": "Model answer: ...",
      "explanation": "Marking guidance: ...",
      "points": 10
    }},
    {{
      "section": "C",
      "question_text": "...",
      "options": [],
      "correct_answer": "Model answer: ...",
      "explanation": "Marking guidance: ...",
      "points": 20
    }}
  ]
}}"""


def _clean_json(text: str) -> str:
    """Strip markdown fences and fix common LLM JSON issues (trailing commas, comments)."""
    text = re.sub(r'^```(?:json)?\s*', '', text)
    text = re.sub(r'\s*```$', '', text)
    # Remove trailing commas before ] or }
    text = re.sub(r',\s*([}\]])', r'\1', text)
    # Remove single-line // comments
    text = re.sub(r'//[^\n]*', '', text)
    return text.strip()


def _generate_mcq_questions(field_display, title, hint):
    from ai_service.views import call_openrouter  # noqa: PLC0415

    prompt = MCQ_PROMPT.format(field_display=field_display, title=title, hint=hint)
    result = call_openrouter(
        prompt,
        model_name=MCQ_MODEL,
        max_tokens=2500,
        read_timeout_override=90,
    )
    text = result.text.strip()
    text = _clean_json(text)
    return json.loads(text).get('questions', [])


def _generate_exam_questions(field_display, title, hint):
    from ai_service.views import call_openrouter  # noqa: PLC0415

    prompt = EXAM_PROMPT.format(field_display=field_display, title=title, hint=hint)
    result = call_openrouter(
        prompt,
        model_name=EXAM_MODEL,
        max_tokens=3500,
        read_timeout_override=120,
    )
    text = result.text.strip()
    text = _clean_json(text)
    return json.loads(text).get('questions', [])


def _validate_question(q):
    opts = q.get('options', [])
    return (
        q.get('question_text') and
        isinstance(opts, list) and len(opts) == 4 and
        q.get('correct_answer') and
        q['correct_answer'] in opts
    )


# ── Command ───────────────────────────────────────────────────────────────────

class Command(BaseCommand):
    help = 'Seed high-quality MCQ assessments for diverse academic disciplines.'

    def add_arguments(self, parser):
        parser.add_argument('--fields', default='',
                            help='Comma-separated field keys to seed (default: all).')
        parser.add_argument('--dry-run', action='store_true', default=False,
                            help='Show what would be created without writing to DB.')
        parser.add_argument('--update', action='store_true', default=False,
                            help='Regenerate and overwrite already-existing assessments.')
        parser.add_argument('--admin-user', default='',
                            help='Email of creator account (default: first superuser).')

    def handle(self, *args, **options):
        from django.contrib.auth import get_user_model
        from assessments.models import Assessment, Question

        User = get_user_model()

        email = options['admin_user']
        if email:
            creator = User.objects.get(email=email)
        else:
            creator = User.objects.filter(is_superuser=True).order_by('id').first()
            if not creator:
                self.stderr.write('No superuser found. Pass --admin-user.')
                return

        dry_run = options['dry_run']
        do_update = options['update']
        requested = set(f.strip() for f in options['fields'].split(',') if f.strip())
        fields_to_run = {k: v for k, v in SUBJECTS.items()
                         if not requested or k in requested}

        if not fields_to_run:
            self.stderr.write(f'No matching fields. Available: {", ".join(SUBJECTS.keys())}')
            return

        self.stdout.write(f'Creator: {creator.email}')
        self.stdout.write(f'Fields : {", ".join(fields_to_run.keys())}')
        total_topics = sum(len(v['topics']) for v in fields_to_run.values())
        self.stdout.write(f'Topics : {total_topics} assessments to generate\n')

        if dry_run:
            self.stdout.write(self.style.WARNING('DRY RUN — no DB writes.\n'))
            for field_key, field_data in fields_to_run.items():
                for title, hint, tags in field_data['topics']:
                    self.stdout.write(f'  [DRY] {field_data["display"]} — {title} (quiz + exam paper)')
            return

        created = updated = skipped = failed = 0

        for field_key, field_data in fields_to_run.items():
            field_display = field_data['display']
            self.stdout.write(self.style.HTTP_INFO(f'\n═══ {field_display} ═══'))
            topic_slug = field_key.replace('_', ' ').title()

            for title, hint, tags in field_data['topics']:

                # ── A: Practice Quiz (10 MCQs) ─────────────────────────────
                quiz_title = f'{title}: Practice Quiz'
                if Assessment.objects.filter(title=quiz_title, creator=creator).exists() and not do_update:
                    self.stdout.write(f'  [SKIP] "{quiz_title}"')
                    skipped += 1
                else:
                    self.stdout.write(f'  Generating quiz: "{quiz_title}"...')
                    try:
                        mcqs = _generate_mcq_questions(field_display, title, hint)
                        valid_mcqs = [q for q in mcqs if _validate_question(q)]
                        if len(valid_mcqs) < 5:
                            raise ValueError(f'Only {len(valid_mcqs)} valid MCQs')

                        quiz_desc = (
                            f'A 10-question practice quiz on {title.split("—")[-1].strip()} in {field_display}. '
                            f'Timed at 20 minutes. Great for quick revision and self-testing.'
                        )
                        existing_quiz = Assessment.objects.filter(title=quiz_title, creator=creator).first()
                        if existing_quiz and do_update:
                            existing_quiz.description = quiz_desc
                            existing_quiz.tags = tags
                            existing_quiz.save()
                            existing_quiz.questions.all().delete()
                            quiz = existing_quiz
                            updated += 1
                            action = 'Updated'
                        else:
                            quiz = Assessment.objects.create(
                                title=quiz_title,
                                topic=topic_slug,
                                description=quiz_desc,
                                creator=creator,
                                time_limit_minutes=20,
                                assessment_type=Assessment.AssessmentType.QUIZ,
                                is_public=True,
                                allow_students_see_results=True,
                                source_year=2024,
                                source_attribution='EduReach Multidisciplinary Library',
                                tags=tags,
                            )
                            created += 1
                            action = 'Created'

                        for order, q in enumerate(valid_mcqs, start=1):
                            Question.objects.create(
                                assessment=quiz,
                                question_text=q['question_text'],
                                question_type=Question.QuestionType.MCQ,
                                options=q.get('options', []),
                                correct_answer=q['correct_answer'],
                                explanation=q.get('explanation', ''),
                                points=1,
                                order=order,
                            )
                        self.stdout.write(self.style.SUCCESS(
                            f'    [{action}] Quiz — {len(valid_mcqs)} MCQs'))
                    except Exception as exc:
                        self.stderr.write(f'    [FAIL] Quiz: {exc}')
                        failed += 1
                    time.sleep(1)

                # ── B: Exam Paper (KU-style: MCQ + Short Answer + Essay) ────
                exam_title = f'{title}: End of Semester Examination'
                if Assessment.objects.filter(title=exam_title, creator=creator).exists() and not do_update:
                    self.stdout.write(f'  [SKIP] "{exam_title}"')
                    skipped += 1
                else:
                    self.stdout.write(f'  Generating exam:  "{exam_title}"...')
                    try:
                        exam_qs = _generate_exam_questions(field_display, title, hint)
                        if len(exam_qs) < 5:
                            raise ValueError(f'Only {len(exam_qs)} exam questions returned')

                        sec_a = [q for q in exam_qs if q.get('section') == 'A']
                        sec_b = [q for q in exam_qs if q.get('section') == 'B']
                        sec_c = [q for q in exam_qs if q.get('section') == 'C']

                        exam_desc = (
                            f'This paper consists of THREE sections.\n'
                            f'SECTION A ({len(sec_a)} questions, compulsory): Multiple choice, 2 marks each.\n'
                            f'SECTION B ({len(sec_b)} questions): Short answer. Attempt ANY TWO. 10 marks each.\n'
                            f'SECTION C ({len(sec_c)} questions): Essay. Attempt ANY ONE. 20 marks.\n'
                            f'Time allowed: 2 hours. Total marks: 50.'
                        )
                        exam_tags = tags + ['exam', 'past paper', 'end of semester', 'ku style']

                        existing_exam = Assessment.objects.filter(title=exam_title, creator=creator).first()
                        if existing_exam and do_update:
                            existing_exam.description = exam_desc
                            existing_exam.tags = exam_tags
                            existing_exam.save()
                            existing_exam.questions.all().delete()
                            exam = existing_exam
                            updated += 1
                            action = 'Updated'
                        else:
                            exam = Assessment.objects.create(
                                title=exam_title,
                                topic=topic_slug,
                                description=exam_desc,
                                creator=creator,
                                time_limit_minutes=120,
                                assessment_type=Assessment.AssessmentType.EXAM,
                                is_public=True,
                                allow_students_see_results=True,
                                source_year=2024,
                                source_attribution='EduReach Multidisciplinary Library',
                                tags=exam_tags,
                            )
                            created += 1
                            action = 'Created'

                        for order, q in enumerate(exam_qs, start=1):
                            sec = q.get('section', 'A')
                            if sec == 'A' and _validate_question(q):
                                Question.objects.create(
                                    assessment=exam,
                                    question_text=f'[Section A] {q["question_text"]}',
                                    question_type=Question.QuestionType.MCQ,
                                    options=q.get('options', []),
                                    correct_answer=q['correct_answer'],
                                    explanation=q.get('explanation', ''),
                                    points=int(q.get('points', 2)),
                                    order=order,
                                )
                            else:
                                # Short answer or essay — ESSAY type
                                section_label = {'B': 'Section B — Short Answer', 'C': 'Section C — Essay'}.get(sec, sec)
                                Question.objects.create(
                                    assessment=exam,
                                    question_text=f'[{section_label}] {q["question_text"]}',
                                    question_type=Question.QuestionType.ESSAY,
                                    options=[],
                                    correct_answer=q.get('correct_answer', ''),
                                    explanation=q.get('explanation', ''),
                                    points=int(q.get('points', 10)),
                                    order=order,
                                )

                        self.stdout.write(self.style.SUCCESS(
                            f'    [{action}] Exam  — {len(sec_a)} MCQ + {len(sec_b)} short answer + {len(sec_c)} essay'))
                    except Exception as exc:
                        self.stderr.write(f'    [FAIL] Exam: {exc}')
                        failed += 1
                    time.sleep(2)  # Slightly longer pause for the heavier model

        self.stdout.write('')
        self.stdout.write(self.style.SUCCESS(
            f'Done — created: {created}, updated: {updated}, skipped: {skipped}, failed: {failed}'
        ))
