# Generated by Django 5.0.1 on 2025-11-11 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(help_text='YouTube video ID', max_length=20)),
                ('notes', models.TextField(blank=True, help_text="User's notes about the video")),
                ('timestamps', models.JSONField(default=list, help_text="List of timestamped notes: [{'time': 120, 'note': 'Important point'}]")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video Notes',
                'verbose_name_plural': 'Video Notes',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'video_id')},
            },
        ),
    ]
