# Generated by Django 5.0.1 on 2025-11-17 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_videonotes'),
        ('courses', '0002_lesson_manual_transcript_lesson_transcript_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='related_lessons',
            field=models.ManyToManyField(blank=True, help_text='Videos tagged as relevant to this assessment', related_name='related_assessments', to='courses.lesson'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='source_lesson',
            field=models.ForeignKey(blank=True, help_text='Lesson this quiz was generated from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_assessments', to='courses.lesson'),
        ),
    ]
