# Generated by Django 5.0.1 on 2026-02-05 02:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_assessment_related_lessons_assessment_source_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='AssessmentAnswerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='assessment_answers/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_images', to='assessments.userattempt')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'unique_together': {('attempt', 'question_id', 'image')},
            },
        ),
    ]
