# Generated by Django 5.0.1 on 2026-02-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_assessment_results_visibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattempt',
            name='time_taken_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userattempt',
            name='xp_earned',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
