# Generated by Django 5.2.12 on 2026-04-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0009_add_question_results_to_userattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='is_proctored',
            field=models.BooleanField(default=False, help_text='When enabled, learners must have camera on and cannot switch tabs freely.'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='proctor_tab_limit',
            field=models.PositiveIntegerField(default=3, help_text='Number of tab-switch violations allowed before the attempt is auto-submitted.'),
        ),
    ]
