# Generated by Django 5.0.1 on 2026-04-30 10:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0010_assessment_is_proctored_assessment_proctor_tab_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assessment',
            unique_together={('creator', 'title')},
        ),
    ]
