# Generated by Django 5.0.1 on 2026-05-01 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0011_alter_assessment_unique_together'),
        ('users', '0010_institution_user_institution_role_user_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='allow_students_see_results',
            field=models.BooleanField(default=True, help_text='When False, only the creator can see student results (useful for contests).'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='institution',
            field=models.ForeignKey(blank=True, help_text='School or organisation this paper comes from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='users.institution'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='source_attribution',
            field=models.CharField(blank=True, help_text='Human-readable credit line, e.g. "Kenyatta University — Engineering, 2023 Final".', max_length=300),
        ),
        migrations.AddField(
            model_name='assessment',
            name='source_year',
            field=models.PositiveIntegerField(blank=True, help_text='Year the original exam was sat (e.g. 2023).', null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='List of searchable tag strings, e.g. ["calculus","engineering","KU"].'),
        ),
    ]
