# Generated by Django 5.0.1 on 2026-05-02 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0014_source_url_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='competition_country',
            field=models.CharField(blank=True, help_text='Competition body or country (e.g. "IMO", "APMO", "Kenya").', max_length=200),
        ),
        migrations.AddField(
            model_name='assessment',
            name='competition_language',
            field=models.CharField(blank=True, help_text='Language the original paper was written in.', max_length=100),
        ),
        migrations.AddField(
            model_name='assessment',
            name='competition_name',
            field=models.CharField(blank=True, help_text='Full name of the specific competition event.', max_length=400),
        ),
        migrations.CreateModel(
            name='QuestionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(help_text='Original filename referenced in markdown (e.g. attached_image_1.png).', max_length=200)),
                ('image', models.ImageField(upload_to='question_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='assessments.question')),
            ],
            options={
                'ordering': ['filename'],
            },
        ),
    ]
