# Generated by Django 5.0.1 on 2026-05-21 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0017_add_tab_tracking_to_attempt'),
        ('curriculum', '0002_unit_topic_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Study unit this paper was explicitly added to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attached_papers', to='curriculum.unit'),
        ),
    ]
