# Generated by Django 5.0.1 on 2026-04-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_cache', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocache',
            name='concepts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='videocache',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videocache',
            name='quizzes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='videocache',
            name='relationships',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
