"""
Auto-tag generation for Assessment objects.

Tags are derived purely from structured fields (no AI call needed for basic tagging).
AI-generated assessments get the 'ai-generated' tag via the view that creates them.
"""
from django.db.models.signals import post_save
from django.dispatch import receiver


# Subject keyword → canonical tag
_SUBJECT_KEYWORDS = {
    'economics': ['economics', 'economic', 'macro', 'micro', 'microeconomics', 'macroeconomics',
                  'gdp', 'inflation', 'monetary', 'fiscal', 'eet'],
    'mathematics': ['math', 'mathematics', 'algebra', 'calculus', 'geometry', 'trigonometry',
                    'statistics', 'probability', 'arithmetic', 'olympiad', 'nmc'],
    'physics': ['physics', 'mechanics', 'thermodynamics', 'electromagnetism', 'optics'],
    'chemistry': ['chemistry', 'organic', 'inorganic', 'stoichiometry', 'thermochemistry'],
    'biology': ['biology', 'cell', 'genetics', 'ecology', 'anatomy', 'physiology'],
    'computer science': ['computer', 'programming', 'algorithm', 'data structure', 'networking',
                         'software', 'database', 'python', 'java', 'coding'],
    'business': ['business', 'accounting', 'finance', 'management', 'marketing', 'entrepreneurship'],
    'history': ['history', 'historical', 'war', 'revolution', 'civilization'],
    'geography': ['geography', 'geographic', 'climate', 'topography', 'cartography'],
    'literature': ['literature', 'poetry', 'novel', 'prose', 'shakespeare', 'grammar', 'english'],
    'kiswahili': ['kiswahili', 'swahili'],
}

_INSTITUTION_KEYWORDS = {
    'ku': 'kenyatta university',
    'uon': 'university of nairobi',
    'mku': 'mount kenya university',
    'jkuat': 'jkuat',
    'strathmore': 'strathmore',
    'usiu': 'usiu',
}

_LEVEL_KEYWORDS = {
    'university': ['university', 'undergraduate', 'degree', 'bsc', 'ba ', 'honours', 'college'],
    'high school': ['high school', 'secondary', 'kcse', 'form 1', 'form 2', 'form 3', 'form 4', 'o-level', 'a-level'],
    'primary': ['primary', 'kcpe', 'grade ', 'std ', 'standard '],
    'olympiad': ['olympiad', 'competition', 'contest', 'nmc', 'imo'],
}


def _generate_tags(assessment) -> list[str]:
    """Return a deduplicated list of tags for `assessment`."""
    tags: set[str] = set()

    # Always include assessment_type and ai flag
    if assessment.assessment_type:
        tags.add(assessment.assessment_type)  # 'quiz' or 'exam'

    # Check for existing ai-generated tag to preserve it
    existing = list(assessment.tags or [])
    if 'ai-generated' in existing:
        tags.add('ai-generated')

    search_text = ' '.join(filter(None, [
        assessment.title or '',
        assessment.topic or '',
        assessment.description or '',
        assessment.source_attribution or '',
    ])).lower()

    # Subject tags
    for tag, keywords in _SUBJECT_KEYWORDS.items():
        if any(kw in search_text for kw in keywords):
            tags.add(tag)

    # Level tags
    for tag, keywords in _LEVEL_KEYWORDS.items():
        if any(kw in search_text for kw in keywords):
            tags.add(tag)

    # Institution name as a tag (short name)
    if assessment.institution:
        inst_name = (assessment.institution.name or '').lower()
        # Try to find a short identifier
        for abbr, full in _INSTITUTION_KEYWORDS.items():
            if full in inst_name or abbr in inst_name:
                tags.add(abbr)
                break
        else:
            # Fall back to first word of institution name (max 20 chars)
            first_word = inst_name.split()[0][:20] if inst_name.split() else ''
            if first_word:
                tags.add(first_word)

    # Year tag if available
    if assessment.source_year:
        tags.add(str(assessment.source_year))

    # Topic as a tag (normalised, max 30 chars)
    if assessment.topic:
        topic_tag = assessment.topic.strip().lower()[:30]
        if topic_tag:
            tags.add(topic_tag)

    return sorted(tags)


@receiver(post_save, sender='assessments.Assessment')
def auto_tag_assessment(sender, instance, created, **kwargs):
    """
    Auto-generate tags whenever an Assessment is saved.
    We skip the save if tags didn't change to avoid an infinite loop.
    """
    new_tags = _generate_tags(instance)

    # Preserve any manually-set tags that aren't in our generated set
    existing = list(instance.tags or [])
    # Manual tags: those not generated by our logic (e.g. custom labels)
    # We merge: keep all existing, add newly derived ones
    merged = sorted(set(existing) | set(new_tags))

    if merged != existing:
        # Use queryset update to avoid triggering post_save recursively
        sender.objects.filter(pk=instance.pk).update(tags=merged)
