# Generated by Django 5.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroupchallenge',
            name='is_public_listing',
            field=models.BooleanField(
                default=False,
                help_text='If True, this challenge appears in the platform Public challenges list for all users to discover.',
            ),
        ),
    ]
