# Generated by Django 5.0.1

from django.db import migrations, models
from django.utils.crypto import get_random_string


def generate_tokens_for_existing_groups(apps, schema_editor):
    """Generate invite tokens for all existing study groups."""
    StudyGroup = apps.get_model('study_groups', 'StudyGroup')
    for group in StudyGroup.objects.filter(invite_token__isnull=True):
        group.invite_token = get_random_string(32)
        group.save()


class Migration(migrations.Migration):

    dependencies = [
        ('study_groups', '0002_studygroupchallenge_is_public_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='invite_enabled',
            field=models.BooleanField(
                default=True,
                help_text='If False, invite links for this group are disabled.',
            ),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='invite_token',
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.RunPython(generate_tokens_for_existing_groups),
    ]
