# Generated by Django 5.0.1 on 2026-04-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_groups', '0003_studygroup_token_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='bulk_payment_active',
            field=models.BooleanField(default=False, help_text='If True, all members of this group inherit premium access.'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='bulk_payment_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
