# Generated by Django 5.0.1 on 2025-11-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='manual_transcript',
            field=models.TextField(blank=True, help_text='Manually pasted transcript as fallback'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='transcript',
            field=models.TextField(blank=True, help_text='Auto-fetched or manually entered transcript'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='transcript_fetched_at',
            field=models.DateTimeField(blank=True, help_text='When transcript was last fetched', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='transcript_language',
            field=models.CharField(default='en', help_text='Transcript language code', max_length=10),
        ),
        migrations.AddField(
            model_name='lesson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='Full YouTube URL', max_length=500),
        ),
    ]
