# Generated by Django 5.0.1 on 2026-05-21 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_personalsession'),
        ('curriculum', '0002_unit_topic_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Curriculum unit this lesson belongs to (mirrors its course).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='curriculum.unit'),
        ),
    ]
