# Generated by Django 5.0.1 on 2026-05-21 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_lesson_unit'),
        ('curriculum', '0005_paperextractionjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='added_by',
            field=models.ForeignKey(blank=True, help_text='User who added this lesson (for edit/delete permission).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_lessons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lesson',
            name='completed_by',
            field=models.ManyToManyField(blank=True, help_text='Users who have marked this lesson complete.', related_name='completed_unit_lessons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Curriculum unit this lesson belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='curriculum.unit'),
        ),
    ]
