# Generated by Django 5.0.1 on 2026-03-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_add_paypal_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(choices=[('mpesa', 'M-Pesa (STK Push)'), ('mpesa_paybill', 'M-Pesa (Paybill)'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card Payment'), ('paypal', 'PayPal / International')], max_length=50, unique=True),
        ),
    ]
