# Generated by Django 5.0.1 on 2026-05-04 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_add_trial_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('learner', 'Starter'), ('pro', 'Pro'), ('pro_plus', 'Pro Plus'), ('admin', 'Admin')], max_length=15),
        ),
    ]
