# Generated by Django 5.0.1 on 2026-05-21 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(choices=[('engineering', 'University / Engineering'), ('olympiad', 'Olympiad Training')], db_index=True, max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, db_index=True, max_length=30)),
                ('institution', models.CharField(blank=True, max_length=200)),
                ('level', models.CharField(blank=True, help_text='e.g. "Year 3, Semester 1" or "National".', max_length=80)),
                ('syllabus_summary', models.TextField(help_text='Topics this unit covers. Injected into AI prompts so the tutor and quiz generator understand the unit instead of producing placeholder text.')),
                ('description', models.CharField(blank=True, max_length=300)),
                ('is_official', models.BooleanField(default=True, help_text='True for seeded/curated units; False for user-created units.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_units', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['track', 'code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserEnrolledUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='curriculum.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_units', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-enrolled_at'],
                'unique_together': {('user', 'unit')},
            },
        ),
    ]
