# Generated by Django 5.0.1 on 2026-05-21 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='topic_keywords',
            field=models.JSONField(blank=True, default=list, help_text="Assessment topic strings this unit maps to. The unit's past papers are the Assessment records whose topic matches one of these (case-insensitive)."),
        ),
    ]
