# Generated by Django 5.0.1 on 2026-05-21 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_lesson_unit'),
        ('curriculum', '0002_unit_topic_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='is_public',
            field=models.BooleanField(default=False, help_text='True if this unit is discoverable by other users in Explore.'),
        ),
        migrations.AddField(
            model_name='unit',
            name='source_course',
            field=models.ForeignKey(blank=True, help_text='The Course this unit was migrated from, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_units', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='track',
            field=models.CharField(choices=[('engineering', 'University / Engineering'), ('olympiad', 'Olympiad Training'), ('general', 'General Course')], db_index=True, max_length=20),
        ),
    ]
