# Generated by Django 5.0.1 on 2026-03-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_coursechannel_discussionthread_threadreply_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='threadreply',
            options={'ordering': ['-is_accepted', '-is_verified', '-created_at'], 'verbose_name': 'Thread Reply'},
        ),
        migrations.RemoveField(
            model_name='threadreply',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='threadvote',
            name='vote_type',
            field=models.CharField(choices=[('helpful', 'Helpful'), ('not_helpful', 'Not Helpful')], default='helpful', max_length=20),
        ),
    ]
