# Generated by Django 5.0.1 on 2026-05-21 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_coursechannel_name_nullable_course'),
        ('curriculum', '0005_paperextractionjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursechannel',
            name='unit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussion_channel', to='curriculum.unit'),
        ),
    ]
