# Generated by Django 5.0.1 on 2026-05-21 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_lesson_unit'),
        ('curriculum', '0004_migrate_courses_to_units'),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='note',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='note',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='curriculum.unit'),
        ),
        migrations.AlterField(
            model_name='note',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='courses.lesson'),
        ),
    ]
