# Generated by Django 5.0.1 on 2025-11-17 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_monthlyusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_trial_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='original_tier',
            field=models.CharField(choices=[('free', 'Free'), ('learner', 'Learner'), ('pro', 'Pro'), ('pro_plus', 'Pro Plus'), ('admin', 'Admin')], default='free', help_text='Tier to revert to after trial ends', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='trial_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
