# Generated by Django 5.0.1 on 2026-02-25 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_trial_active_user_original_tier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='show_xp_publicly',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='total_time_spent_seconds',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='xp_points',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='XPTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('transaction_type', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('assessment', 'Assessment Completion'), ('course', 'Course/Lesson Progress'), ('streak', 'Daily Streak'), ('bonus', 'Achievement Bonus'), ('challenge', 'Study Group Challenge')], default='bonus', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
