# Generated by Django 5.0.1 on 2026-04-29 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_add_notification_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('challenge', 'Challenge'), ('system', 'System'), ('trial_started', 'Trial Started'), ('trial_expiring', 'Trial Expiring'), ('trial_expired', 'Trial Expired'), ('payment_success', 'Payment Successful'), ('payment_failed', 'Payment Failed'), ('level_up', 'Level Up'), ('study_reminder', 'Study Reminder'), ('assessment_graded', 'Assessment Graded')], default='system', max_length=20),
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(unique=True)),
                ('p256dh', models.TextField()),
                ('auth', models.TextField()),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
