# Generated by Django 5.0.1 on 2026-05-08 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_topic_mastery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('challenge', 'Challenge'), ('system', 'System'), ('trial_started', 'Trial Started'), ('trial_expiring', 'Trial Expiring'), ('trial_expired', 'Trial Expired'), ('payment_success', 'Payment Successful'), ('payment_failed', 'Payment Failed'), ('level_up', 'Level Up'), ('study_reminder', 'Study Reminder'), ('assessment_graded', 'Assessment Graded'), ('missing_transcript', 'Missing Transcript')], default='system', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='original_tier',
            field=models.CharField(choices=[('free', 'Free'), ('learner', 'Starter'), ('pro', 'Pro'), ('pro_plus', 'Pro Plus'), ('admin', 'Admin')], default='free', help_text='Tier to revert to after trial ends', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('learner', 'Starter'), ('pro', 'Pro'), ('pro_plus', 'Pro Plus'), ('admin', 'Admin')], default='free', max_length=10),
        ),
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('is_guest', models.BooleanField(default=False)),
                ('converted', models.BooleanField(default=False)),
                ('page', models.CharField(blank=True, max_length=100)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['first_seen'], name='users_sitev_first_s_fe10d6_idx'), models.Index(fields=['is_guest'], name='users_sitev_is_gues_6bf848_idx'), models.Index(fields=['converted'], name='users_sitev_convert_0260d7_idx')],
            },
        ),
    ]
