# Generated by Django 5.0.1 on 2026-05-04 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_topic_mastery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('challenge', 'Challenge'), ('system', 'System'), ('trial_started', 'Trial Started'), ('trial_expiring', 'Trial Expiring'), ('trial_expired', 'Trial Expired'), ('payment_success', 'Payment Successful'), ('payment_failed', 'Payment Failed'), ('level_up', 'Level Up'), ('study_reminder', 'Study Reminder'), ('assessment_graded', 'Assessment Graded'), ('missing_transcript', 'Missing Transcript')], default='system', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='original_tier',
            field=models.CharField(choices=[('free', 'Free'), ('learner', 'Starter'), ('pro', 'Pro'), ('pro_plus', 'Pro Plus'), ('admin', 'Admin')], default='free', help_text='Tier to revert to after trial ends', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('learner', 'Starter'), ('pro', 'Pro'), ('pro_plus', 'Pro Plus'), ('admin', 'Admin')], default='free', max_length=10),
        ),
    ]
