# Generated by Django 5.0.1 on 2026-05-08 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_add_site_visit'),
    ]

    operations = [
    ]
