# Generated by Django 5.0.1 on 2026-05-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_merge_20260508_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('challenge', 'Challenge'), ('system', 'System'), ('trial_started', 'Trial Started'), ('trial_expiring', 'Trial Expiring'), ('trial_expired', 'Trial Expired'), ('payment_success', 'Payment Successful'), ('payment_failed', 'Payment Failed'), ('level_up', 'Level Up'), ('study_reminder', 'Study Reminder'), ('assessment_graded', 'Assessment Graded'), ('missing_transcript', 'Missing Transcript'), ('feature_announcement', 'Feature Announcement'), ('continue_learning', 'Continue Learning'), ('new_content', 'New Content Available'), ('achievement_near', 'Achievement Near')], default='system', max_length=20),
        ),
    ]
