# Generated by Django 5.0.1 on 2026-05-14 02:56

from django.db import migrations, models


def mark_existing_users_onboarded(apps, schema_editor):
    """
    Mark existing users who already have a learning_goal set as having
    completed onboarding, so they don't see the post-auth onboarding modal.
    """
    User = apps.get_model('users', 'User')
    User.objects.filter(learning_goal__isnull=False).exclude(learning_goal='').update(onboarding_completed=True)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_add_smart_notification_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, help_text='Country of residence.', max_length=60),
        ),
        migrations.AddField(
            model_name='user',
            name='degree_course',
            field=models.CharField(blank=True, help_text='Specific degree or course name, e.g. BSc Computer Science.', max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_completed',
            field=models.BooleanField(default=False, help_text='Set to True once the user has completed the post-signup onboarding flow.'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number in E.164-like format, e.g. 254712345678.', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='year_of_study',
            field=models.CharField(blank=True, help_text='Year/form in study, e.g. Year 2, Form 3.', max_length=20),
        ),
        migrations.RunPython(
            mark_existing_users_onboarded,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
