# Generated by Django 5.0.1 on 2026-05-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_add_onboarding_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='track',
            field=models.CharField(blank=True, choices=[('unset', 'Not set'), ('engineering', 'University Exam Prep'), ('olympiad', 'Olympiad Training'), ('both', 'Both')], default='unset', help_text='Which study experience the user picked: engineering exam prep, olympiad training, or both.', max_length=20),
        ),
    ]
