# Generated by Django 5.0.1 on 2026-05-11 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EngineeringProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.CharField(max_length=255)),
                ('unit_code', models.CharField(db_index=True, max_length=20)),
                ('unit_name', models.CharField(max_length=255)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('year', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('semester', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('paper_type', models.CharField(blank=True, max_length=100)),
                ('question_number', models.CharField(max_length=20)),
                ('question_text', models.TextField()),
                ('marks', models.CharField(blank=True, max_length=20)),
                ('question_type', models.CharField(blank=True, max_length=50)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, default='medium', max_length=10)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('has_diagram', models.BooleanField(default=False)),
                ('diagram_image', models.ImageField(blank=True, null=True, upload_to='engineering/diagrams/')),
                ('diagram_description', models.TextField(blank=True)),
                ('model_solution', models.TextField(blank=True)),
                ('solution_status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'AI Generated'), ('verified', 'Verified')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['unit_code', 'year', 'question_number'],
                'unique_together': {('source_file', 'question_number')},
            },
        ),
    ]
