# Generated by Django 5.0.1 on 2026-05-21 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
        ('engineering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineeringproblem',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engineering_problems', to='curriculum.unit'),
        ),
    ]
